# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a04218cc90b98d929c0dfcdade6ff4e091d7709e47622d50743a2a785b879bc30838245ad664aa6459f918cd00d5afd44437c514a412a3795214fe9b974f16bb

test:
  secret_key_base: 4516a72ff5e628a31b2482b44f164a81b96d96724cacac67b27df7eed5d2a2891249b65c2d8813a9ebc08ab9c168c8cdcf0ab460713c8033db9a73ca6c46ed25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
